apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ticbq2xmg-nodejs 
  janus-idp.io/tekton: ticbq2xmg-nodejs
  backstage.io/kubernetes-id: ticbq2xmg-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ticbq2xmg-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  