apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ticbq2xmg-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ticbq2xmg-nodejs 
  name: ticbq2xmg-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: ticbq2xmg-nodejs 
